# 1. Change prefix from Ctrl+B to Option+Space (Meta-Space)
unbind C-b
set -g prefix M-Space
bind M-Space last-window
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# 2. Base settings
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -s escape-time 0
set -g detach-on-destroy off
set -g mouse on
set -g status-justify absolute-centre
set -g status-position top

# 3. Fix colors for Kitty and LazyVim
set-option -g default-terminal "screen-256color"
set-option -sa terminal-features ',xterm-kitty:RGB'

# 4. Window Splitting
bind-key "'" split-window -h -c '#{pane_current_path}'
bind-key '\' split-window -h -c '#{pane_current_path}'
bind-key - split-window -v -c '#{pane_current_path}'
bind-key = split-window -v -c '#{pane_current_path}'
bind-key c new-window -c '#{pane_current_path}'

# 5. Use vim-style pane resizing
bind-key -r left resize-pane -L 2
bind-key -r down resize-pane -D 2
bind-key -r up resize-pane -U 2
bind-key -r right resize-pane -R 2

# 6. Vi Copy Mode
bind P paste-buffer
bind-key -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection

# 7. Use vim-style pane switching
bind-key H next-layout
bind-key J swap-pane -D
bind-key K swap-pane -U

# 8. Load Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
